# Poseidon — personal-assistant ZeroClaw daemon
#
# Runs a single zeroclaw daemon as a dedicated `poseidon` system user with
# strong filesystem hardening:
#   - ProtectHome=tmpfs hides /home from the unit by default
#   - BindReadOnlyPaths / BindPaths re-expose only the directories you opt in
#   - POSIX ACLs (via systemd-tmpfiles) grant the poseidon user the matching
#     read / read+write permissions on those host paths
#
# The agent itself enforces an additional autonomy layer (level + forbidden
# paths) so a misbehaving model still gets blocked before it touches anything
# it shouldn't.
{
  lib,
  pkgs,
  config,
  ...
}:
with lib;
let
  cfg = config.poseidon;
  matrixEnabled = cfg.matrix.roomId != "";

  allowedRoots = cfg.bindReadOnlyPaths ++ cfg.bindReadWritePaths;
  allowedRootsLine =
    if allowedRoots != [ ] then
      "allowed_roots = [${concatMapStringsSep ", " (p: ''"${p}"'') allowedRoots}]"
    else
      "";

  forbiddenPathsLine =
    "forbidden_paths = [${concatMapStringsSep ", " (p: ''"${p}"'') cfg.autonomy.forbiddenPaths}]";

  matrixSection = optionalString matrixEnabled ''

    [channels_config.matrix]
    homeserver = "${cfg.matrix.homeserverUrl}"
    access_token = "@MATRIX_ACCESS_TOKEN@"
    room_id = "${cfg.matrix.roomId}"
    allowed_users = [${concatMapStringsSep ", " (u: ''"${u}"'') cfg.matrix.allowedUsers}]
    stream_mode = "partial"
    draft_update_interval_ms = 1500
  '';

  configTemplate = pkgs.writeText "poseidon-config.toml" ''
    # Poseidon ZeroClaw config — generated by NixOS module
    default_provider = "${cfg.provider}"
    default_model = "${cfg.model}"
    default_temperature = ${toString cfg.temperature}

    [providers.ollama]
    base_url = "${cfg.ollamaBaseUrl}"

    [agent]
    max_tool_iterations = 999999
    parallel_tools = false

    [autonomy]
    level = "${cfg.autonomy.level}"
    workspace_only = ${if cfg.autonomy.workspaceOnly then "true" else "false"}
    ${forbiddenPathsLine}
    ${allowedRootsLine}

    [gateway]
    host = "127.0.0.1"
    port = ${toString cfg.gatewayPort}
    allow_public_bind = false
    ${matrixSection}
  '';

  prestart = pkgs.writeShellApplication {
    name = "poseidon-prestart";
    runtimeInputs = [ pkgs.coreutils pkgs.gnused ];
    text = builtins.readFile ./prestart.sh;
  };
in
{
  options.poseidon = {
    enable = mkEnableOption "Poseidon — personal-assistant zeroclaw daemon";

    user = mkOption {
      type = types.str;
      default = "poseidon";
    };

    group = mkOption {
      type = types.str;
      default = "poseidon";
    };

    workspaceBaseDir = mkOption {
      type = types.str;
      default = "/var/lib/poseidon";
      description = "Home directory for the poseidon user. ZeroClaw writes ~/.zeroclaw/ here.";
    };

    provider = mkOption {
      type = types.enum [ "ollama" "anthropic" "openai" "openrouter" "groq" "deepseek" ];
      default = "ollama";
    };

    model = mkOption {
      type = types.str;
      default = "qwen3.6:35b-a3b";
    };

    temperature = mkOption {
      type = types.float;
      default = 0.7;
    };

    ollamaBaseUrl = mkOption {
      type = types.str;
      default = "http://127.0.0.1:11434";
    };

    gatewayPort = mkOption {
      type = types.port;
      default = 42618;
      description = "Local HTTP gateway port (must differ from the dev orchestrator's 42617).";
    };

    identityFile = mkOption {
      type = types.path;
      default = ./IDENTITY.md;
    };

    bindReadOnlyPaths = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [ "/home/beat/Documents" ];
      description = ''
        Host paths bind-mounted read-only into Poseidon's mount namespace,
        plus an ACL granting the poseidon user read access. The agent's
        autonomy.allowed_roots list is automatically populated from this.
      '';
    };

    bindReadWritePaths = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [ "/home/beat/SynologyDrive/Poseidon" ];
      description = ''
        Host paths bind-mounted read-write, plus an ACL granting the poseidon
        user read+write access. Use sparingly: each entry here widens the
        blast radius of a misbehaving agent.
      '';
    };

    autonomy = {
      level = mkOption {
        type = types.enum [ "readonly" "supervised" "full" ];
        default = "supervised";
        description = "Higher levels skip more confirmation prompts. `supervised` is the safe default for a personal assistant.";
      };

      workspaceOnly = mkOption {
        type = types.bool;
        default = false;
        description = "If true, writes are confined to ~/.zeroclaw/ regardless of bindReadWritePaths.";
      };

      forbiddenPaths = mkOption {
        type = types.listOf types.str;
        default = [
          "/etc"
          "/root"
          "/sys"
          "/proc"
          "/boot"
          "/home/beat/.ssh"
          "/home/beat/.gnupg"
          "/home/beat/.config/sops"
          "/home/beat/.local/share/keyrings"
          "/home/beat/.aws"
          "/home/beat/.kube"
        ];
        description = "Agent-level denylist. Defense-in-depth on top of the bind-mount allowlist.";
      };
    };

    matrix = {
      homeserverUrl = mkOption {
        type = types.str;
        default = "https://matrix.shetec.ch";
      };

      roomId = mkOption {
        type = types.str;
        default = "";
        description = "Matrix room ID. Empty disables matrix integration.";
      };

      allowedUsers = mkOption {
        type = types.listOf types.str;
        default = [ ];
      };

      accessTokenFile = mkOption {
        type = types.nullOr types.path;
        default = null;
        description = ''
          Path to a file containing `MATRIX_ACCESS_TOKEN=...`, readable by the
          poseidon user. Typically a sops-nix secret declared with
          `owner = config.poseidon.user`.
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.group;
      home = cfg.workspaceBaseDir;
      createHome = true;
      shell = pkgs.bash;
      description = "Poseidon personal assistant service user";
    };
    users.groups.${cfg.group} = { };

    environment.systemPackages = [ pkgs.zeroclaw ];

    systemd.tmpfiles.rules =
      [
        "d ${cfg.workspaceBaseDir} 0750 ${cfg.user} ${cfg.group} -"
        "d ${cfg.workspaceBaseDir}/.zeroclaw 0750 ${cfg.user} ${cfg.group} -"
        "d ${cfg.workspaceBaseDir}/.zeroclaw/state 0750 ${cfg.user} ${cfg.group} -"
        "d ${cfg.workspaceBaseDir}/.zeroclaw/workspace 0750 ${cfg.user} ${cfg.group} -"
        "d ${cfg.workspaceBaseDir}/.zeroclaw/workspace/skills 0750 ${cfg.user} ${cfg.group} -"
        "L+ ${cfg.workspaceBaseDir}/.zeroclaw/workspace/IDENTITY.md - - - - ${cfg.identityFile}"
      ]
      ++ map (p: "A+ ${p} - - - - u:${cfg.user}:rX,d:u:${cfg.user}:rX,m::rwx,d:m::rwx") cfg.bindReadOnlyPaths
      ++ map (p: "A+ ${p} - - - - u:${cfg.user}:rwX,d:u:${cfg.user}:rwX,m::rwx,d:m::rwx") cfg.bindReadWritePaths;

    systemd.services.poseidon = {
      description = "Poseidon personal assistant daemon";
      after = [ "network-online.target" ] ++ optional (config.services.ollama.enable or false) "ollama.service";
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      environment = {
        HOME = cfg.workspaceBaseDir;
      };

      path = [ pkgs.bash pkgs.coreutils pkgs.gnused pkgs.git pkgs.openssh ];

      serviceConfig = {
        Type = "simple";
        User = cfg.user;
        Group = cfg.group;
        WorkingDirectory = cfg.workspaceBaseDir;

        EnvironmentFile = optional (matrixEnabled && cfg.matrix.accessTokenFile != null) "-${cfg.matrix.accessTokenFile}";

        ExecStartPre = "${prestart}/bin/poseidon-prestart ${configTemplate} ${if matrixEnabled then "matrix" else "no-matrix"}";
        ExecStart = "${pkgs.zeroclaw}/bin/zeroclaw daemon";

        Restart = "on-failure";
        RestartSec = 10;

        # --- Hardening ---
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = "tmpfs";
        PrivateTmp = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictSUIDSGID = true;
        LockPersonality = true;

        ReadWritePaths = [ cfg.workspaceBaseDir ];
        BindReadOnlyPaths = cfg.bindReadOnlyPaths;
        BindPaths = cfg.bindReadWritePaths;
      };
    };
  };
}
