{
  config,
  pkgs,
  lib,
  ...
}:
with lib;
let
  cfg = config.niri;

  workspacesKdl =
    let
      lines = concatLists (
        mapAttrsToList (
          monitor: tags:
          map (tag: ''workspace "${toString tag}" { open-on-output "${monitor}"; }'') tags
        ) cfg.workspaces
      );
    in
    pkgs.writeText "workspaces.kdl" ''
      // Generated by Nix — do not edit
      ${concatStringsSep "\n" lines}
    '';
in
{
  imports = [
    ../noctalia/noctalia.nix
    ../rofi/rofi.nix
    ../dunst/dunst.nix
  ];

  options.niri = {
    enable = mkEnableOption "niri";

    workspaces = mkOption {
      type = types.attrsOf (types.listOf types.int);
      default = { };
      example = {
        "DP-1" = [ 1 2 3 ];
        "DP-2" = [ 4 5 6 ];
        "HDMI-1" = [ 7 8 9 ];
      };
      description = "Map of monitor output names to their fixed workspace tags.";
    };
  };

  config = mkIf cfg.enable {
    noctalia.enable = true;

    xdg.configFile."niri/config.kdl".source =
      config.lib.file.mkOutOfStoreSymlink config.home.homeDirectory
      + "/.nix/modules/home-manager/niri/config.kdl";

    xdg.configFile."niri/workspaces.kdl" = mkIf (cfg.workspaces != { }) {
      source = workspacesKdl;
    };

    home.packages = with pkgs; [
      wl-clipboard
      grim
      grimblast
      slurp
      playerctl
      brightnessctl
      rofi
      swaynotificationcenter
    ];
  };
}
