# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "thunderbolt"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "amdgpu"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/12b22954-be1d-479f-b043-23f6d86bc9a0";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0652-A23A";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/24199abb-f69c-484d-b68a-79ad4c01b261"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp10s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth = {
    enable = true;
    settings = {
      General = {
        Name = "Hello";
        ControllerMode = "dual";
        FastConnectable = "true";
        Experimental = "true";
      };
      Policy = {
        AutoEnable = "true";
      };
    };
  };

  hardware.fancontrol = {
    enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon11=devices/pci0000:00/0000:00:02.1/0000:05:00.0/0000:06:0c.0/0000:6b:00.0/usb5/5-7/5-7:1.1/0003:0C70:F011.000B hwmon8=devices/pci0000:00/0000:00:02.1/0000:05:00.0/0000:06:0c.0/0000:6b:00.0/usb5/5-6/5-6:1.1/0003:0C70:F012.0006
      DEVNAME=hwmon11=octo hwmon8=highflownext
      FCTEMPS=hwmon11/pwm6=hwmon8/temp1_input hwmon11/pwm4=hwmon8/temp1_input hwmon11/pwm3=hwmon8/temp1_input hwmon11/pwm2=hwmon8/temp1_input hwmon11/pwm1=hwmon8/temp1_input
      FCFANS=hwmon11/pwm6=hwmon11/fan6_input hwmon11/pwm4=hwmon11/fan4_input hwmon11/pwm3=hwmon11/fan3_input hwmon11/pwm2=hwmon11/fan2_input hwmon11/pwm1=hwmon11/fan1_input
      MINTEMP=hwmon11/pwm6=20 hwmon11/pwm4=20 hwmon11/pwm3=20 hwmon11/pwm2=20 hwmon11/pwm1=20
      MAXTEMP=hwmon11/pwm6=40 hwmon11/pwm4=40 hwmon11/pwm3=40 hwmon11/pwm2=40 hwmon11/pwm1=40
      MINSTART=hwmon11/pwm6=150 hwmon11/pwm4=150 hwmon11/pwm3=150 hwmon11/pwm2=150 hwmon11/pwm1=150
      MINSTOP=hwmon11/pwm6=100 hwmon11/pwm4=100 hwmon11/pwm3=100 hwmon11/pwm2=100 hwmon11/pwm1=100
    '';
  };
}
