# Agent workspace directories, config.toml generation, and identity files
#
# Each agent gets its own home directory at:
#   <workspaceBaseDir>/<name>/
#     .zeroclaw/
#       config.toml
#       workspace/
#         IDENTITY.md
#         skills/
#
# Agent profiles are defined in agent-profiles/<name>.nix with:
#   - identity: IDENTITY.md content
#   - autonomy: [autonomy] TOML section
#   - delegate: (optional) config for the orchestrator's [agents.<name>] section
#
# ZeroClaw reads ~/.zeroclaw/ relative to HOME, so each systemd service
# sets HOME to the agent's directory.
#
{
  lib,
  pkgs,
  config,
  ...
}:
with lib;
let
  cfg = config.agenticLoop;

  agentNames = [
    "orchestrator"
    "planner"
    "coder"
    "reviewer"
    "tester"
    "deployer"
    "monitor"
  ];

  enabledAgents = filter (name: cfg.agents.${name}.enable) agentNames;

  # Load agent profiles from individual files
  profiles = listToAttrs (
    map (name: nameValuePair name (import ./agent-profiles/${name}.nix)) agentNames
  );

  # Build delegate agent TOML sections for the orchestrator
  # Only agents that are enabled AND have a delegate config get included
  delegateSection =
    let
      delegatableAgents = filter (name:
        cfg.agents.${name}.enable
        && (profiles.${name} ? delegate)
        && name != "orchestrator"
        && name != "monitor"
      ) agentNames;
    in
    concatMapStrings (name:
      let
        agentCfg = cfg.agents.${name};
        d = profiles.${name}.delegate;
        toolsList = concatMapStringsSep ", " (t: ''"${t}"'') d.allowedTools;
      in ''

[agents.${name}]
provider = "${agentCfg.provider}"
model = "${agentCfg.model}"
agentic = ${if d.agentic then "true" else "false"}
agentic_timeout_secs = ${toString d.timeoutSecs}
max_iterations = ${toString d.maxIterations}
allowed_tools = [${toolsList}]
system_prompt = "${lib.escape [ ''"'' "\\" ] d.systemPrompt}"
'') delegatableAgents;

  # Generate config.toml for an agent
  mkConfigToml =
    name:
    let
      agentCfg = cfg.agents.${name};
      profile = profiles.${name};
      matrixSection =
        if cfg.matrix.roomId != "" && (name == "orchestrator" || name == "monitor") then
          ''

[channels_config.matrix]
homeserver = "${cfg.matrix.homeserverUrl}"
access_token = "@MATRIX_ACCESS_TOKEN@"  # substituted at activation time
room_id = "${if name == "monitor" && cfg.matrix.alertRoomId != "" then cfg.matrix.alertRoomId else cfg.matrix.roomId}"
allowed_users = [${
              concatMapStringsSep ", " (u: ''"${u}"'') (if cfg.matrix.allowedUsers == [] then [ "*" ] else cfg.matrix.allowedUsers)
            }]
stream_mode = "partial"
draft_update_interval_ms = 1500
''
        else
          "";
      # Only orchestrator gets delegate agent sections
      delegates = if name == "orchestrator" then delegateSection else "";
    in
    pkgs.writeText "zeroclaw-${name}-config.toml" ''
# ZeroClaw config for ${name} agent — generated by NixOS module
default_provider = "${agentCfg.provider}"
default_model = "${agentCfg.model}"
default_temperature = ${toString agentCfg.temperature}

[agent]
max_tool_iterations = 200
parallel_tools = false

${profile.autonomy}

[gateway]
host = "0.0.0.0"
port = 42617
allow_public_bind = true
${matrixSection}${delegates}
'';

  # Generate IDENTITY.md for an agent
  mkIdentityFile =
    name:
    let
      agentCfg = cfg.agents.${name};
      profile = profiles.${name};
    in
    if agentCfg.identityFile != null then
      agentCfg.identityFile
    else
      pkgs.writeText "IDENTITY-${name}.md" profile.identity;

  # Wrapper script for on-demand agent invocation
  mkInvokeScript =
    name:
    pkgs.writeShellScript "agentic-invoke-${name}" ''
      export HOME="${cfg.workspaceBaseDir}/${name}"
      exec ${pkgs.zeroclaw}/bin/zeroclaw agent -m "$@"
    '';
in
{
  # Expose generated paths for use by other sub-modules
  options.agenticLoop._internal = {
    configFiles = mkOption {
      type = types.attrsOf types.path;
      internal = true;
      default = { };
    };
    identityFiles = mkOption {
      type = types.attrsOf types.path;
      internal = true;
      default = { };
    };
    invokeScripts = mkOption {
      type = types.attrsOf types.path;
      internal = true;
      default = { };
    };
  };

  config = mkIf cfg.enable {
    # Generate all internal paths for enabled agents
    agenticLoop._internal.configFiles = listToAttrs (
      map (name: nameValuePair name (mkConfigToml name)) enabledAgents
    );
    agenticLoop._internal.identityFiles = listToAttrs (
      map (name: nameValuePair name (mkIdentityFile name)) enabledAgents
    );
    agenticLoop._internal.invokeScripts = listToAttrs (
      map (name: nameValuePair name (mkInvokeScript name)) enabledAgents
    );

    # Create directory structure
    systemd.tmpfiles.rules = concatMap (name: [
      "d ${cfg.workspaceBaseDir}/${name} 0750 ${cfg.user} ${cfg.group} -"
      "d ${cfg.workspaceBaseDir}/${name}/.zeroclaw 0750 ${cfg.user} ${cfg.group} -"
      "d ${cfg.workspaceBaseDir}/${name}/.zeroclaw/workspace 0750 ${cfg.user} ${cfg.group} -"
      "d ${cfg.workspaceBaseDir}/${name}/.zeroclaw/workspace/skills 0750 ${cfg.user} ${cfg.group} -"
      "d ${cfg.workspaceBaseDir}/${name}/.zeroclaw/state 0750 ${cfg.user} ${cfg.group} -"
      # Symlink IDENTITY.md from nix store (or custom path)
      "L+ ${cfg.workspaceBaseDir}/${name}/.zeroclaw/workspace/IDENTITY.md - - - - ${cfg._internal.identityFiles.${name}}"
    ]) enabledAgents;

    # Generate config.toml at activation time, substituting secrets
    # Config is written (not symlinked) so we can inject the Matrix access token
    system.activationScripts.agentic-loop-configs = {
      text = concatMapStrings (name:
        let
          template = cfg._internal.configFiles.${name};
          configPath = "${cfg.workspaceBaseDir}/${name}/.zeroclaw/config.toml";
          hasMatrixToken = cfg.apiKeys.matrixTokenFile != null
            && cfg.matrix.roomId != ""
            && (name == "orchestrator" || name == "monitor");
        in ''
          # Generate config for ${name}
          rm -f ${configPath}
          ${if hasMatrixToken then ''
            MATRIX_TOKEN=$(${pkgs.gnugrep}/bin/grep -oP 'MATRIX_ACCESS_TOKEN=\K.*' ${cfg.apiKeys.matrixTokenFile} || cat ${cfg.apiKeys.matrixTokenFile})
            ${pkgs.gnused}/bin/sed "s|@MATRIX_ACCESS_TOKEN@|$MATRIX_TOKEN|g" ${template} > ${configPath}
          '' else ''
            cp ${template} ${configPath}
          ''}
          chown ${cfg.user}:${cfg.group} ${configPath}
          chmod 600 ${configPath}
        ''
      ) enabledAgents;
    };

    # Install invoke scripts to a shared bin directory
    environment.systemPackages = [
      (pkgs.symlinkJoin {
        name = "agentic-loop-scripts";
        paths = map (
          name:
          pkgs.writeShellScriptBin "agentic-invoke-${name}" ''
            export HOME="${cfg.workspaceBaseDir}/${name}"
            exec ${pkgs.zeroclaw}/bin/zeroclaw agent -m "$@"
          ''
        ) enabledAgents;
      })
    ];
  };
}
