#!/bin/bash

case $- in
# Enable the subsequent settings only in interactive sessions
*i*) ;;
*) return ;;
esac

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Path to your oh-my-bash installation.
export OSH="${HOME}/.oh-my-bash"
export SYSTEMD_EDITOR=vim
# export GIT_EDITOR="NVR --remote-tab-wait + 'set bufhidden=delete'"

# TODO: fix the command to act like I actually want
# export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"

fzfe() {
  echo -n "" | fzf --print-query --prompt="Enter regex> " --preview='echo {} | highlight --syntax regex'
}

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-bash is loaded.
OSH_THEME="gravel_pit"

PATH="$HOME/.local/bin/:$PATH"

# To disable the uses of "sudo" by oh-my-bash, please set "false" to
# this variable.  The default behavior for the empty value is "true".
export OMB_USE_SUDO=true

# Which completions would you like to load? (completions can be found in ~/.oh-my-bash/completions/*)
# Custom completions may be added to ~/.oh-my-bash/custom/completions/
# Example format: completions=(ssh git bundler gem pip pip3)
# Add wisely, as too many completions slow down shell startup.
completions=(
  git
  composer
  ssh
)

# Which aliases would you like to load? (aliases can be found in ~/.oh-my-bash/aliases/*)
# Custom aliases may be added to ~/.oh-my-bash/custom/aliases/
# Example format: aliases=(vagrant composer git-avh)
# Add wisely, as too many aliases slow down shell startup.
aliases=(
  # general
)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-bash/plugins/*)
# Custom plugins may be added to ~/.oh-my-bash/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  bashmarks
)

# Which plugins would you like to conditionally load? (plugins can be found in ~/.oh-my-bash/plugins/*)
# Custom plugins may be added to ~/.oh-my-bash/custom/plugins/
# Example format:
#  if [ "$DISPLAY" ] || [ "$SSH" ]; then
#      plugins+=(tmux-autoattach)
#  fi

# shellcheck source=/home/beat/.oh-my-bash/oh-my-bash.sh
source "$OSH"/oh-my-bash.sh

vpn() {
  local target="$1"
  local state="$2"

  nmcli connection "$state" "$target"
}

pacmanSearch() {
  pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
}

export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"

if [[ -f "$HOME/.aliases" ]]; then
  . "$HOME/.aliases"
fi

if [[ -f "$HOME/.aliases_mt" ]]; then
  . "$HOME/.aliases_mt"
fi

if [[ -f "$HOME/.bashrc_mt" ]]; then
  . "$HOME/.bashrc_mt"
fi

set +o noclobber
